schemaVersion=2
runtimeBackend=rootfs_proot
architecture=aarch64
baseImage=debian:trixie-20260824
debianSnapshot=20260830T000000Z
runtimePackages=hangover-latest,box64-wine-latest
graphicsDrivers=rootfs-virgl-mesa,rootfs-llvmpipe
dxWrappers=rootfs-wined3d,rootfs-dxvk-2.7,rootfs-dxvk-3.1,rootfs-dxvk-1.10.3
audioDrivers=pulseaudio
