#!/data/data/com.termux/files/usr/bin/sh
ASSET_TMP="${HOME}/.termux/tmp"
trap 'rm -f "$ASSET_TMP/install" "$ASSET_TMP/xkeyboard-config_2.45_all.deb" "$ASSET_TMP/termux-x11-nightly-1.03.10-0-all.deb"' EXIT
pkg remove termux-x11-nightly -y
dpkg -i "$ASSET_TMP/xkeyboard-config_2.45_all.deb"
dpkg -i "$ASSET_TMP/termux-x11-nightly-1.03.10-0-all.deb"
chmod +x /data/data/com.termux/files/usr/libexec/termux-x11/loader.apk
chmod +x /data/data/com.termux/files/usr/bin/startxserver
chmod +x /data/data/com.termux/files/usr/bin/stopserver
chmod +x /data/data/com.termux/files/usr/bin/termux-x11
chmod +x /data/data/com.termux/files/usr/bin/termux-display
chmod +x /data/data/com.termux/files/usr/bin/termux-x11-preference
