package com.termux.localgames.runtime;

public enum PreflightIssueCode {
    PERMISSION_LOST,
    PROVIDER_UNAVAILABLE,
    GAME_ROOT_NOT_POSIX_ACCESSIBLE,
    RUNTIME_UNAVAILABLE,
    RUNTIME_PROVISION_REQUIRED,
    UNSUPPORTED_PROFILE_SELECTION,
    COMPONENT_UNKNOWN,
    COMPONENT_VERSION_UNAVAILABLE,
    COMPONENT_MISSING,
    COMPONENT_VERSION_MISMATCH,
    STORAGE_INSUFFICIENT
}
